### ISSUE TITLE
Feature Request: Flavour Text

### ISSUE THREAD

**Issue by dalmationer** [lizardqueenlexi/orbstation#10]
I think it would be cool to have the option to set flavour text in the character setup. These should all be optional but might be cool for roleplaying. The fields I think we should have are:

### Description

> A quick description that appears when someone examines your character. Should be short and to-the-point. Has a More Info button below.

### Detailed description

> A more detailed description which appears when someone clicks on the description button. Has the option to contain a small (200x200px ish) image of your character (e.g. an illustration or picrew.) which would have to be hosted elsewhere, e.g. on imgur or discord.

### Aura

> The colour and texture of your aura, which can be examined by magical beings such as wizards, heretics and particularly gonzo detectives.

### Medical Record

> A short blurb which appears in the medical records console on roundstart. Some good RP with doctors maybe. 

### Security Record

> A short blurb which appears in the security records console on roundstart. Could be cool if you want to play someone who has security keeping an eye on you. 

### Why it would be good for the game

I think this would open some more room for imagining our cool characters and roleplaying, plus it's entirely optional so you can play without it if it's too much hassle to write out a big blurb.

**Comment by lizardqueenlexi** [comment]
Description feature added in #245. It'd be nice to have medical and security record customization, still. For now, I'm not planning to implement character images, but that may change in the future.
