### ISSUE TITLE
Zombies are too strong / too boring

### ISSUE THREAD

**Issue by Jacquerel** [lizardqueenlexi/orbstation#121]
Every time we have created zombies from the traitor objective people have reported frustration at the end of the round.
Zombies are very difficult to kill (or at least, kill permanently) and can kill _you_ with a single attack.
This event clearly isn't designed for our population but we can probably fix it to at least be more acceptable.

Some suggested fixes:

- Romerol/Romerol Tumors should do no damage but turn you into a zombie upon dying from other means. The traitor starting the event must actually kill someone or inject an existing corpse, and just getting scratched once isn't a ticking death sentence.
- Zombies should have a _chance_ to get back up when killed without decapitation, not a guarantee. Add a chance for their head to simply disintegrate when killed, likely increasing every time they die.

The event can surely also be fixed in other ways, it simply needs to accomplish the objective of causing chaos and fear without turning most of the crew into zombies almost as a guarantee.

**Comment by lizardqueenlexi** [comment]
Resolved by #127
