### ISSUE TITLE
Feature Request: Tram Illiteracy

### ISSUE THREAD

**Issue by lizardqueenlexi** [lizardqueenlexi/orbstation#140]
Currently, if you have the Illiterate trait, you can still operate the Lavaland Shuttle Consoles. This is, presumably, a mandatory feature so that illiterate miners can actually do their jobs. Clicking these consoles while illiterate causes you to randomly smash buttons, which, after a progress bar fills, moves the shuttle.

Presently, being illiterate makes it impossible to move the tram, as you cannot use the control console. It would be nice if this was not the case - a similar "button mashing" could be implemented fairly easily, and could possibly, after a short delay, move the tram to a random station. This would be more fun than simply being unable to use it, while still coming with a funny downside.

**Comment by Profakos** [comment]
Should be sent upstream.

**Comment by Jacquerel** [comment]
Implemented upstream
