### ISSUE TITLE
Minor Feature Request: Boggle Goggles craftable with cable coils as well as cloth

### ISSUE THREAD

**Issue by skylord-a52** [lizardqueenlexi/orbstation#145]
Cloth can be really hard to find, and I know cables were considered at one point, so it'd be great if you could craft them with either. I tried to add a second recipe myself, but it always ended up just overwriting the first.

**Comment by Profakos** [comment]
Cloth is not hard to find, you can get it by using cutting tools on bedsheets, which are common.
