### ISSUE TITLE
Feature Request: More Prescription Eyewear

### ISSUE THREAD

**Issue by lizardqueenlexi** [lizardqueenlexi/orbstation#159]
Currently, the nearsighted quirk is needlessly terrible for some jobs, as it prevents you from using _anything_ else that fits in the eye slot. Some of these, like mesons and medical HUDs, are indispensable for a lot of jobs. I propose that there should be prescription versions of these items, allowing you to continue doing your job while also having glasses.

**Comment by Jacquerel** [comment]
Any glasses can be this now.
