### ISSUE TITLE
Enable persistence files

### ISSUE THREAD

**Issue by Profakos** [lizardqueenlexi/orbstation#17]
The following files and or folders have to be created to enable persistence, because it looks like they are not created automatically, unless if i am incorrect.

- [x] data/picture_logs/
- [x] data/paintings.json
- [x] data/engravings/[SSmapping.config.map_name]_engravings.json // one per each map?
- [x] data/engravings/prisoner_tattoos.json
- [x] data/photo_albums.json
- [x] data/photo_frames.json
- [x] data/npc_saves/TrophyItems.json
- [x] data/RandomizedChemRecipes.json

There is a save file for scars but its created automatically per person i think?

**Comment by lizardqueenlexi** [comment]
These files and folders _were_ actually created automatically. Thus, there is no problem.
