### ISSUE TITLE
Character Customization: Character Description

### ISSUE THREAD

**Issue by lizardqueenlexi** [lizardqueenlexi/orbstation#171]
You should be able to set a customized description for your character, which might appear when your character is examined. This would allow much deeper personalization of a character past the very rudimentary and extremely same-y in-game character sprites. Likely, we would want some kind of character limit on this feature.

It has also been suggested to allow linking to a character image, though we would want to consider this carefully due to the risks associated with allowing external image linking.

**Comment by Jacquerel** [comment]
This might require some careful consideration of how it actually works with regards to game mechanics. 
Is it tied to your Mind, the Body you start with, or your ID Card? 
Does it still display if you are transformed into a monkey, or rebrained into a different body? What if your DNA is modified to match someone else's, or brain is swapped by a wizard?
Do changelings inherit your examine text?
Is this text blocked by simply wearing enough clothes to be "Unknown"?

**Comment by lizardqueenlexi** [comment]
Added in #245
