### ISSUE TITLE
Refactor Removals

### ISSUE THREAD

**Issue by Jacquerel** [lizardqueenlexi/orbstation#182]
We have largely removed all the objectionable content we didn't like from the game (though we're still finding some occasionally), now that we've done that we should go back and redo it in a way that is healthier for the code long-term.
Generally speaking this means that in every instance where we have touched TG code directly, we should see if there is a way to make that change in the Orbstation folder instead in order to prevent merge conflicts.

For items which are removed this entails putting them back and overriding any instance which creates them.
This won't be possible in all instances, but there are several where it should be.

**Comment by flowercuco** [comment]
is this closed as of lexi's removal refactor?
