### ISSUE TITLE
Get Rid of Acting Captain Antags

### ISSUE THREAD

**Issue by lizardqueenlexi** [lizardqueenlexi/orbstation#189]
This is mostly a problem at our population where we rarely have a captain, but acting captain antags aren't _fun_. For anyone. They can go anywhere they want and do anything they want, and the rest of the crew is relatively powerless to stop them. And, unfortunately, we seem to get them every other round.

The issue lies in how roundstart antags are assigned - jobs, and by consequence, Acting Captain, are assigned _after_ antag roles. Heads of staff can be antags, and Acting Captain is assigned according to a strict chain of command. Thus, there is no easy way to make this not happen.

One way we could prevent this easily is to destroy the chain of command - make all heads of staff equal and randomly roll between them for who gets Acting Captain. This may not be ideal, and I do feel like Head of Personnel should still always be second-in-command, which could still lead to the same problem.

Another route, which may or may not be possible, could involve automatically _removing_ antag status from whoever gets assigned as the Acting Captain after jobs are assigned. The threat spent on them could be placed into the midround threat budget instead. This might be a bit janky of a solution, but it doesn't seem impossible to do.

If anyone has any other ideas, please do comment.

**Comment by Jacquerel** [comment]
To summarise a discord discussion we had about this: 
Randomising the Chain of Command seems possible and also comes with other upsides (people can play RD without a 90% chance of also being Captain). It does not ultimately solve the problem though, as it leaves cases where there is still only one head of staff.
Deantagging is harder by virtue of the existence of things like Blood Brother.
PL suggested that there are complaints about this same feature even in the tg forums, so it is plausible that we could create a config option and send it upstream for reordering the order of events such that acting captain is also chosen before antagonist status, though this would necessitate including the randomised chain of command.

**Comment by lizardqueenlexi** [comment]
This is functionally resolved by #441, unless the HoP rolls antag while also getting acting captain - which can simply be handled by admins. I think it's fine to close this for now.
