### ISSUE TITLE
Replacement recipes

### ISSUE THREAD

**Issue by Profakos** [lizardqueenlexi/orbstation#19]
Needs a new recipe for: 
"omegasoapification" reaction in code/modules/reagents/chemistry/recipes/others.dm
"scream" reaction in code/modules/reagents/chemistry/recipes/others.dm

New grind reulst for:
"Omega Soap" in code/game/objects/items/clown_items.dm

I recommend Protein Blend for soap, but i don't think that is rare enough for Scream.

**Comment by lizardqueenlexi** [comment]
Resolved by #180
