### ISSUE TITLE
Change: Remove scanner gates

### ISSUE THREAD

**Issue by jade-lavenza** [lizardqueenlexi/orbstation#20]
Scanner gates, as found in `code/game/machinery/scan_gate.dm`, have a lot of questionable bits about them—species-based scanning (maybe it should be replaced with only the zombie-detecting functionality), detecting the 'fat' status, etc. They also appear to only be mapped in as a subtype on the emergency luxury shuttle, which doesn't even use any of this functionality anyway—it just withdraws money from a character's account on entering.

Frankly, I don't see a compelling reason to keep any of this—maybe the disease, arrest status, gun, and zombie scanning, but that's about it.

**Comment by Profakos** [comment]
Closing this as finished, the rest of the content is fine. Honestly reading what scanners gate do, I would have used it as a food dispenser that dispenses species specific food, but oh well. 😔
