### ISSUE TITLE
LOOC typing indicators

### ISSUE THREAD

**Issue by lizardqueenlexi** [lizardqueenlexi/orbstation#309]
It would be extremely useful if LOOC chat had its own unique typing indicator icon. LOOC currently suffers from the issue where whoever's near you can't tell you're typing, so they might just walk away in the middle even if you're trying to convey something important.

An important consideration is, unlike regular typing indicators, LOOC can be used even if you're unconscious, dead, or otherwise unable to talk. Ideally, LOOC indicators will appear above whatever mob you control regardless of its state, including things like being inside of a disembodied brain or severed head. The indicators should also be distinctive so that they can't be easily missed or confused for regular speech indicators. Otherwise, they can work essentially the same as existing indicators.

**Comment by flowercuco** [comment]
ill give this a shot tmoz, ill let you know if i give up lol

**Comment by flowercuco** [comment]
i cant even figure out how the lawyer badge gives you a different speech icon lmao

i guess that its like

we'd probably want LOOC_typing.dm that starts with /mob/proc/create_LOOC_indicator()

and move/living/create_LOOC_indicator
is like, 
`	if(active_typing_indicator || active_thinking_indicator || ((some variable or something else that sets it to detect LOOC))
		return FALSE
	active_typing_indicator = ((looc talk files))', "[bubble_icon]0", TYPING_LAYER)
	add_overlay(active_typing_indicator)
	play_fov_effect(src, 6, "talk", ignore_self = TRUE)`
	
and then the same/similar remove code

i guess maybe its like LOOC_thinking or LOOC_typing gets added to mob/living variables and is set as false at first and then we make a variable that detects if you have the looc say open to make it true and use that? but i dont know how to do that im sorry.

**Comment by lizardqueenlexi** [comment]
Added in #435
