### ISSUE TITLE
Feature Request: Department Assistants!

### ISSUE THREAD

**Issue by dalmationer** [lizardqueenlexi/orbstation#34]
Make assistants spawn with a little extra access based on what the player's chosen security department is:

Some aliases could be:
service: butler
engineering: technician 
science: lab tech
cargo: Postie
security: Clerk
medical: nurse

No more greytide, much more actual assisting! I might need to make some department-specific assistant outfits if need-be.

**Comment by lizardqueenlexi** [comment]
Added in #284
