### ISSUE TITLE
Change: Rebalance Objectives

### ISSUE THREAD

**Issue by lizardqueenlexi** [lizardqueenlexi/orbstation#4]
Certain objectives need to be adjusted/removed for lowpop. For example, "steal 10 ID cards" as a thief when there are only ten players on at all.

**Comment by Profakos** [comment]
https://github.com/tgstation/tgstation/blob/b4fb8f3ed1bfcf8c83ac9e348441733b296a0b44/code/modules/antagonists/thief/thief_objectives.dm#L121 

Found the all access objective. It randomly picks a number from 6 to 10 right now.

**Comment by lizardqueenlexi** [comment]
The thief has been removed, making this issue a moot point.
