### ISSUE TITLE
Escape Alive (Progression Traitor)

### ISSUE THREAD

**Issue by Jacquerel** [lizardqueenlexi/orbstation#47]
The "Progression Traitor" system does not require any traitor to escape alive after completing their objectives.
While this hasn't significantly effected player success rate (more traitors fail than succeed, by a wide margin) many people have commented that it is unsatisfying as a traitor to be noted as succeeding despite death, and unsatisfying as a crewmember that incarcerating a traitor on the shuttle has no effect on whether they are successful.

It would likely be fairly trivial to reintroduce a mandatory "survive/escape alive/escape alone/die gloriously" objective, however it may be preferable (and more within the spirit of the mode) to make it optional.

If possible it would be ideal to generate a random "survive"-style objective and then add a checkbox to accept it within the objectives UI. 
This should award some reputation and possibly also Telecrystals, in order to incentivise taking it (which may actually increase our traitor success rate, despite making it more difficult).
This should be a separate UI element from normal objective selection so as not to permanently occupy one of your limited objective-selection slots.
This option should likely not be selectable once the shuttle has been called, at that point it's a bit too late to commit.
You should not be able to deselect this option once selected, so it should likely have a confirmation prompt before sealing your choice.

It's possible that satisfying these criteria would be persuasive to the tg codebase such that they would accept a PR and maintain it for us, if not then we can maintain it ourselves.

Potentially, completing a Final Objective while alive should satisfy this condition as well as escaping on the shuttle.

**Comment by lizardqueenlexi** [comment]
Resolved by #78
