### ISSUE TITLE
Low-population assassination rep scaling is tuned poorly

### ISSUE THREAD

**Issue by Jacquerel** [lizardqueenlexi/orbstation#48]
Currently assassination objectives reward significantly less reputation than it seems like they should.
These should be one of the riskier and more impactful objectives, however currently there's much less incentive to do them because they are not very rewarding.

ProfessorLizzard identified some causes within the objective scaling code.

One value to examine is TRAITOR_IDEAL_PLAYER_COUNT within game_options.txt
This configuration is within the server options, so we should be able to modify it without touching the code.

The default value is 20, which is less than our usual starting count. 
If fewer people than this are present traitors gain less reputation, especially for assassinations.
Setting it somewhere closer to 10 may remedy some of our problems.

Another value to examine is progression_scaling_deviance.
This modifies your point rewards based on how much time has passed.
Currently it is set to "20 minutes" while assassination has a value of "30 minutes" which means that assassination rewards the least points 10 minutes into the round and most at 50 minutes into the round.
We may wish to adjust this also in order to adjust when objectives become rewarding, and when final objectives begin to appear.

It is also possible that the reputation rewards for assassinations are simply too low to begin with, listed as "2 minutes" of progrssion compared to higher values for apparently easier objectives.
Modifying this should be a later resort than changes which do not require modification to what is probably fairly volatile code.

**Comment by lizardqueenlexi** [comment]
Resolved by #78
