### ISSUE TITLE
Traitor Objective: Minor Vandalism (Posters and Grafitti)

### ISSUE THREAD

**Issue by Jacquerel** [lizardqueenlexi/orbstation#49]
Low reward, early objective to place syndicate posters (perhaps one, perhaps a small amount of them).
Should be rewarded upon being viewed by a certain number of unique people, or after giving out a certain number of negative moodlets (the latter allows the same person to tick the progress meter multiple times).

Slightly higher tier, similar objective to place a 3x3 syndicate grafitti on the ground. 
This is much more difficult to conceal, and takes longer to apply than a poster.
Pays out in a similar fashion.

**Comment by lizardqueenlexi** [comment]
Implemented in #148
