### ISSUE TITLE
Feature Request: Situational Music

### ISSUE THREAD

**Issue by lizardqueenlexi** [lizardqueenlexi/orbstation#6]
Determine if it's possible to play music based on events, or only based on location in the map.

**Comment by dalmationer** [comment]
I like the idea of a CLUNK and a whirring down sound that plays if the station loses power, or a low ambient hum which constantly plays, but stops when atmos is turned off.

**Comment by lizardqueenlexi** [comment]
I don't think this is much of a priority right now, so I'm closing this one down.
