### ISSUE TITLE
Feature Request: Carry More Animals

### ISSUE THREAD

**Issue by lizardqueenlexi** [lizardqueenlexi/orbstation#62]
Currently, you can pick up and carry corgis (and maybe other animals too?). It would be fun if this was extended to more animal types in some capacity. Probably not _all_ simplemobs, but any where it makes since (like chickens).

**Comment by Profakos** [comment]
Research to see who can be picked up: anyone with can_be_held = TRUE

So far this is: foxes, frogs, rabbits, mice, sloth, lizards, pais, drones, cats, bees, dogs.

**Comment by lizardqueenlexi** [comment]
Most animals actually _can_ already be picked up, but not all station pets are included. Maybe add parrots?
