### ISSUE TITLE
Improve Sleeper Surgery Objectives

### ISSUE THREAD

**Issue by Jacquerel** [lizardqueenlexi/orbstation#69]
Currently a lot of the sleeper surgery objectives are funny but not very direct. They should give you some kind of actual aim to base play around.
We should also make it clear that you should not immediately give away the person who did the surgery on you.

Additionally, sleeper surgery always inflicts the same quite debilitating phobia. We should change it to a list, or maybe remove the phobia application entirely as it is both annoying and a bit of a giveaway.

**Comment by lizardqueenlexi** [comment]
Resolved by #78
