### ISSUE TITLE
Feature Request: Shiptest admin music volume knob

### ISSUE THREAD

**Issue by skylord-a52** [lizardqueenlexi/orbstation#80]
Does what it says on the tin.

May attempt to port this over myself.

See also https://github.com/lizardqueenlexi/orbstation/issues/79, which uses the same knob UI element.

**Comment by lizardqueenlexi** [comment]
This actually already exists, but only functions for the "Play Internet Sound" music feature - which is likely what the admins on Shiptest are using as well. Closing this for now, though it may be re-opened if we want to talk about adding a volume knob for "play global sound" as well.
