### ISSUE TITLE
Feature request: Immediate deadchat access upon death

### ISSUE THREAD

**Issue by skylord-a52** [lizardqueenlexi/orbstation#81]
In the Shiptest codebase, you hear deadchat the moment you die, rather than when your ghost leaves your body. This means that you don't have to worry about missing things when you first die and are still in your body, or when you return to your body because somebody's trying to revive you.

I may try to implement this in our codebase in the future.

**Comment by skylord-a52** [comment]
This has been partially fixed by tgui, however, you still have to leave your body in order to hear living people speak.

**Comment by Jacquerel** [comment]
@skylord-a52 do we want to fix this?
Leaving your body as a requirement to hear the living seems desirable, if you think you are imminently going to be revived then you can choose not to listen to things you would have to try to forget.

**Comment by skylord-a52** [comment]
Gonna go ahead and close this issue -- I personally find it annoying that you can miss livechat if you don't leave your body fast enough, but it's not a huge deal and others might like it.

**Comment by skylord-a52** [comment]
.

**Comment by skylord-a52** [comment]
Ooops. Should not have closed as completed, but as not planned instead. Lets see if this works...
