### ISSUE TITLE
Office Bugs should do something

### ISSUE THREAD

**Issue by Jacquerel** [lizardqueenlexi/orbstation#89]
Office bugs are boring and nobody really cares if they are there or not, they should do something to encourage people to actually want to remove them.
tgstation might be happy to accept this if we PRed it, maybe.

Suggestions:

Period muting of the department radio for some short period of time
Manual muting of the department radio for some short peroid of time (maybe both)
Failure to send messages on local radio (some messages simply do not appear, but can be resent, different to a general blackout as it is just a chance per message)
Insertion of random messages into local radio
Mild garbling of messages on local radio
Messages send to general channel instead of specific channels

**Comment by lizardqueenlexi** [comment]
No longer particularly relevant, since this objective was removed. Still, these ideas aren't bad for if someone decides to PR a new version of room bugging upstream or somethinig.
